#!/bin/sh

SESSION='railsdev'

# if the session is already running, just attach to it.
tmux has-session -t $SESSION
if [ $? -eq 0 ]; then
    echo "Session $SESSION already exists. Attaching."
    tmux -2 attach -t $SESSION
    exit 0;
fi

if [ -z "$1" ]
then
    echo "Error: Must specify a valid rails application directory"
    exit 0;
else
    WORKINGDIR=$1
fi

tmux start-server
tmux new-session -d -s $SESSION -n shell
tmux new-window -t $SESSION:1 -n vim
tmux new-window -t $SESSION:2 -n console
tmux new-window -t $SESSION:3 -n tests
tmux new-window -t $SESSION:4 -n log
tmux new-window -t $SESSION:5 -n server

tmux send-keys -t $SESSION:0 "cd $WORKINGDIR; clear" C-m
tmux send-keys -t $SESSION:1 "cd $WORKINGDIR; clear; vs" C-m
tmux send-keys -t $SESSION:2 "cd $WORKINGDIR; clear; rails console" C-m
tmux send-keys -t $SESSION:3 "cd $WORKINGDIR; clear; bundle exec rspec spec/" C-m
tmux send-keys -t $SESSION:4 "cd $WORKINGDIR; clear; tail -f log/development.log" C-m
tmux send-keys -t $SESSION:5 "cd $WORKINGDIR; clear; rails server" C-m

tmux select-window -t $SESSION:0
tmux -2 attach-session -d -t $SESSION

