#!/usr/bin/env ruby
# Assumes plugin is given in the form "git_hub_user/repo_name"
# which will generate a link "http://github.com/git_hub_user/repo_name
# clone to directory vim.linkme/bundle/repo_name

plugin = ARGV[0] 
remote_repo = "http://github.com/#{plugin}.git"
clone_dir = "vim.linkme/bundle/#{plugin.split('/').last}"
puts "Adding submodule to #{clone_dir} from remote repository at #{remote_repo}"
`git submodule add #{remote_repo} #{clone_dir}`               

