#!/bin/bash

bakdir=~/old_dotfiles
mkdir $bakdir

# Checks if file already exists with the name of the link to be
# created.  if so, moves it to a specified backup directory
function linkup {
    if [ -e $2 ]; then
        mv $2 $bakdir
        echo "Moved $2 to $bakdir"
    fi
    ln -s $1 $2
    echo "$1 <- $2 soft link created"
}

# Create home dir soft links to files in ~/.dotfiles
linkup .dotfiles/bashrc ~/.bashrc
linkup .dotfiles/vimrc ~/.vimrc
linkup .dotfiles/gvimrc ~/.gvimrc
linkup .dotfiles/vim ~/.vim
linkup .dotfiles/xmonad ~/.xmonad
linkup .dotfiles/emacs.d ~/.emacs.d
linkup .dotfiles/emacs ~/.emacs
linkup .dotfiles/zshrc ~/.zshrc
linkup .dotfiles/zsh ~/.zsh
linkup .dotfiles/pentadactylrc ~/.pentadactylrc
linkup .dotfiles/Xmodmap ~/.Xmodmap
linkup .dotfiles/Xresources ~/.Xresources
linkup .dotfiles/xmobarrc ~/.xmobarrc
linkup .dotfiles/bin ~/bin

# Update vim plugin git submodules
git submodule init
git submodule update

# Additional setup for vim command-t plugin
cd vim/bundle/command-t/ruby/command-t
ruby extconf.rb
rake make
