;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-backward-char
	evil-backward-word-begin
	evil-emacs-state
	evil-end-of-line
	evil-exit-emacs-state
	evil-find-char
	evil-first-non-blank
	evil-forward-char
	evil-forward-word-begin
	evil-insert
	evil-next-line
	evil-normal-state
	evil-paredit-delete
	evil-previous-line
	evil-visual-char
	kill-region
	paredit-backward-barf-sexp
	paredit-backward-slurp-sexp
	paredit-forward-barf-sexp
	paredit-forward-slurp-sexp
	paredit-splice-sexp
	paredit-split-sexp
	))

(setq mc/cmds-to-run-once
      '(
	evil-next-visual-line
	evil-previous-visual-line
	evil-scroll-line-to-center
	evil-window-delete
	))
