(defun comint-delchar-or-eof-or-kill-buffer (arg)
  (interactive "p")
  (if (null (get-buffer-process (current-buffer)))
      (kill-buffer)
    (comint-delchar-or-maybe-eof arg)))

(add-hook 'comint-mode-hook (lambda ()
			      (local-set-key (kbd "C-u") 'comint-kill-input)
			      (local-set-key (kbd "C-w") 'backward-kill-word)
			      (local-set-key (kbd "C-c C-k") 'kill-line)
			      (local-set-key (kbd "C-p") 'comint-previous-input)
			      (local-set-key (kbd "C-n") 'comint-next-input)
			      (local-set-key (kbd "C-c C-h") 'helm-comint-input-ring)
			      (local-set-key (kbd "C-d") 'comint-delchar-or-eof-or-kill-buffer)
			      (setq-local show-trailing-whitespace nil)))

(provide 'comint-config)
