;; Default faces for when a theme doesn't set them well enough itself
(custom-set-faces
 '(helm-action ((t (:underline t))))
 '(helm-buffer-directory ((t (:foreground "#6E9B26"))))
 '(helm-ff-directory ((t (:background "#668B8B" :foreground "#D0BF8F"))))
 '(helm-ff-executable ((t (:foreground "#EE799F"))))
 '(helm-ff-file ((t (:inherit font-lock-builtin-face :foreground "#D0BF8F"))))
 '(helm-header ((t (:inherit header-line))))
 '(helm-selection ((t (:background "#3C3836" :underline t))))
 '(helm-source-header ((t (:background "#2B2B2B" :foreground "#F0DFAF" :box (:line-width -1 :style released-button) :underline nil :weight bold :height 1.3 :family "Sans Serif"))))
 '(helm-visible-mark ((t (:background "#D0BF8F" :foreground "#3F3F3F"))))
 '(ido-subdir ((t (:foreground "#668B8B"))))
 '(org-done ((((class color) (min-colors 89)) (:bold t :weight bold :foreground "#008700" :background "#d7ff87" :box (:line-width 1 :style none)))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#a1db00"))))
 '(shm-current-face ((t (:background "#606060")))))
