#!/bin/sh

export NODE_PATH='/usr/local/lib/jsctags/':$NODE_PATH
export LANG=en_US.UTF-8

export PATH="$HOME/build/sbt/bin":"$HOME/code/pagezero/bin":"$HOME/scripts":"$HOME/.cabal/bin":"$HOME/.gem/ruby/1.9.1/bin":$PATH

export SCALA_HOME="$HOME/build/scala-2.10.2/"
export PATH="$SCALA_HOME/bin":$PATH
export PATH="$HOME/code/darkdynasty/bin":$PATH
export PATH="$HOME/code/jetpack/bin":$PATH
export PYTHONPATH="$HOME/code/jetpack/src":$PYTHONPATH
# Important for emacsclient.. makes it start the server if it is not already running.
export ALTERNATE_EDITOR=""

# Python virtual environment stuff

# Virualenvwrapper setup
export WORKON_HOME=~/.virtualenvs/
source /etc/bash_completion.d/virtualenvwrapper

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

 # If not running interactively, do not do anything, otherwise startup
 # tmux
[[ $- != *i* ]] && return                 
[[ $TERM != "screen-256color" ]] # && tmuxgo # && exit

# fan control function - fan 0 to turn off fan
function fan() {
  echo level $@ | sudo tee /proc/acpi/ibm/fan
}

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000000
HISTFILESIZE=2000000

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# For RVM function
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# For tmuxinator
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

# For gpg-agent
. $HOME/scripts/gpg-agent.sh
GPG_TTY=$(tty)
export GPG_TTY
